name = "hyphenation"
version = "0.2.0"

description = "Pure-Gleam implementation of Knuthâ€“Liang Hyphenation."
licences = ["Apache-2.0"]
repository = { type = "github", user = "jonathanmfung", repo = "hyphenation" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
simplifile = "~> 1.6"

[dev-dependencies]
gleeunit = "~> 1.0"
